services:
#####################################################
# backend
#####################################################
  backend:
      build:
        context: ./Backend
        dockerfile: backend.Dockerfile
      container_name: backend
      volumes:
        - ./Backend:/var/www/html

      networks:
        - auth-network
      depends_on:
        - db
      

#####################################################
# reverb (Laravel WebSockets)
#####################################################
  reverb:
      build:
        context: ./Backend
        dockerfile: backend.Dockerfile
      container_name: reverb
      working_dir: /var/www/html
      command: php artisan reverb:start --host=0.0.0.0 --port=8080
      restart: unless-stopped
      volumes:
        - ./Backend:/var/www/html
      networks:
        - auth-network
      depends_on:
        - backend
        - redis

#####################################################
# redis
#####################################################
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - auth-network

#####################################################
# nginx
#####################################################
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
      - "6001:6001"
    volumes:
      - ./Backend:/var/www/html
      - ./Nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    networks:
      - auth-network
    depends_on:
      - backend
      - reverb

#####################################################
# DATABASE (MySQL)
#####################################################
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./Mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - auth-network
#####################################################
# PHPMYADMIN (MySQL)
#####################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - auth-network

#####################################################
# FrontEnd (React)
#####################################################            
  frontend:
    build:
      context: ./Frontend
      dockerfile: frontend.Dockerfile
    container_name: frontend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - auth-network
    depends_on:
      - backend

volumes:
  db_data: {}
  nginx_config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./Nginx/laravel.conf
networks:
  auth-network:
    driver: bridge